/**
 * MSW service-worker entrypoint for the browser (FE-1 §D).
 *
 * Activated only when `NEXT_PUBLIC_API_MOCKING=enabled` via the
 * `<MSWProvider>` boot guard in app/layout.tsx. The worker script
 * itself lives at /public/mockServiceWorker.js (generated by
 * `pnpm exec msw init public/`).
 */

import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);
